let allCountriesEN = 
["Angola",
"Antigua and Barbuda",
"Afghanistan",
"Albania",
"United Arab Emirates",
"Argentina",
"Armenia",
"Australia",
"Austria",
"Azerbaijan",
"Burundi",
"Belgium",
"Benin",
"Burkina Faso",
"Bangladesh",
"Bulgaria",
"Bahrain",
"Bahamas",
"Bosnia and Herzegovina",
"Belarus",
"Belize",
"Bolivia",
"Brazil",
"Barbados",
"Brunei",
"Bhutan",
"Botswana",
"Central African Republic",
"Canada",
"Switzerland",
"Chile",
"China",
"Ivory Coast",
"Cameroon",
"Democratic Republic of the Congo",
"Republic of Congo",
"Colombia",
"Comoros",
"Cape Verde",
"Costa Rica",
"Cuba",
"Cyprus",
"Czech Republic",
"Germany",
"Djibouti",
"Dominica",
"Denmark",
"Greenland",
"Dominican Republic",
"Algeria",
"Ecuador",
"Egypt",
"Eritrea",
"Spain",
"Canary Islands (Spain)",
"Estonia",
"Ethiopia",
"Faeroe Islands",
"Falkland Islands",
"Finland",
"Fiji",
"France",
"French Polynesia",
"Saint-Barthélemy",
"Saint-Martin",
"French Guiana",
"Federated States of Micronesia",
"Gabon",
"United Kingdom",
"Cayman Islands",
"Turks and Caicos Islands",
"Georgia",
"Ghana",
"The Gambia",
"Guinea",
"Guinea-Bissau",
"Equatorial Guinea",
"Greece",
"Grenada",
"Guadeloupe",
"Guatemala",
"Guam",
"Guyana",
"Honduras",
"Croatia",
"Haiti",
"Hungary",
"Indonesia",
"India",
"Ireland",
"Iran",
"Iraq",
"Iceland",
"Israel",
"Italy",
"Jamaica",
"Jordan",
"Japan",
"Kazakhstan",
"Kenya",
"Kosovo",
"Kyrgyzstan",
"Cambodia",
"Kiribati",
"Saint Kitts and Nevis",
"South Korea",
"Kuwait",
"Laos",
"Lebanon",
"Liberia",
"Libya",
"Saint Lucia",
"Liechtenstein",
"Sri Lanka",
"Lesotho",
"Lithuania",
"Luxembourg",
"Latvia",
"Morocco",
"Monaco",
"Moldova",
"Madagascar",
"Maldives",
"Mexico",
"Marshall Islands",
"Martinique",
"Macedonia",
"Mali",
"Malta",
"Myanmar",
"Montenegro",
"Mongolia",
"Mozambique",
"Mauritania",
"Mauritius",
"Malawi",
"Malaysia",
"Mayotte",
"Namibia",
"Niger",
"Nigeria",
"Nicaragua",
"Netherlands",
"North Korea",
"Northern Mariana Islands",
"Norway",
"Nepal",
"Nauru",
"New Zealand",
"Oman",
"Pakistan",
"Panama",
"Peru",
"Philippines",
"Palau",
"Palestine",
"Papua New Guinea",
"Poland",
"Portugal",
"Puerto Rico",
"Paraguay",
"Qatar",
"Romania",
"Russia",
"Rwanda",
"Saudi Arabia",
"Sudan",
"Senegal",
"Singapore",
"Solomon Islands",
"Sierra Leone",
"El Salvador",
"San Marino",
"Somalia",
"Serbia",
"South Sudan",
"São Tomé and Principe",
"Suriname",
"Slovakia",
"Slovenia",
"Sweden",
"Swaziland",
"Seychelles",
"Syria",
"Chad",
"Togo",
"Thailand",
"Tajikistan",
"Taiwan",
"Turkmenistan",
"Timor-Leste",
"Tonga",
"Trinidad and Tobago",
"Tunisia",
"Turkey",
"Tuvalu",
"Tanzania",
"Uganda",
"Ukraine",
"Uruguay",
"United States",
"Uzbekistan",
"Vatican City",
"Saint Vincent and the Grenadines",
"Venezuela",
"Vietnam",
"Vanuatu",
"Western Sahara",
"Samoa",
"Yemen",
"South Africa",
"Zambia",
"Zimbabwe"]

let allCountriesNO = 
["Angola",
"Antigua og Barbuda",
"Afghanistan",
"Albania",
"De forente arabiske emirater",
"Argentina",
"Armenia",
"Australia",
"Østerrike",
"Aserbajdsjan",
"Burundi",
"Belgia",
"Benin",
"Burkina Faso",
"Bangladesh",
"Bulgaria",
"Bahrain",
"Bahamas",
"Bosnia-Hercegovina",
"Hviterussland",
"Belize",
"Bolivia",
"Brasil",
"Barbados",
"Brunei",
"Bhutan",
"Botswana",
"Den sentralafrikanske republikk",
"Canada",
"Sveits",
"Chile",
"Kina",
"Elfenbenskysten",
"Kamerun",
"Den demokratiske republikken Kongo",
"Republikken Kongo",
"Colombia",
"Komorene",
"Kapp Verde",
"Costa Rica",
"Cuba",
"Kypros",
"Tsjekkia",
"Tyskland",
"Djibouti",
"Dominica",
"Danmark",
"Grønland",
"Den dominikanske republikken",
"Algeria",
"Ecuador",
"Egypt",
"Eritrea",
"Spania",
"Kanariøyene (Spania)",
"Estland",
"Etiopia",
"Færøyene",
"Falklandsøyene",
"Finland",
"Fiji",
"Frankrike",
"Fransk Polynesia",
"Saint-Barthélemy",
"Saint-Martin",
"Fransk Guyana",
"Federerte stater i Mikronesia",
"Gabon",
"Storbritannia",
"Caymanøyene",
"Turks- og Caicosøyene",
"Georgia",
"Ghana",
"Gambia",
"Guinea",
"Guinea-Bissau",
"Ekvatorial Guinea",
"Hellas",
"Grenada",
"Guadeloupe",
"Guatemala",
"Guam",
"Guyana",
"Honduras",
"Kroatia",
"Haiti",
"Ungarn",
"Indonesia",
"India",
"Irland",
"Iran",
"Irak",
"Island",
"Israel",
"Italia",
"Jamaica",
"Jordan",
"Japan",
"Kasakhstan",
"Kenya",
"Kosovo",
"Kirgisistan",
"Kambodsja",
"Kiribati",
"Saint Kitts og Nevis",
"Sør-Korea",
"Kuwait",
"Laos",
"Libanon",
"Liberia",
"Libya",
"Saint Lucia",
"Liechtenstein",
"Sri Lanka",
"Lesotho",
"Litauen",
"Luxembourg",
"Latvia",
"Marokko",
"Monaco",
"Moldova",
"Madagaskar",
"Maldivene",
"Mexico",
"Marshalløyene",
"Martinique",
"Makedonia",
"Mali",
"Malta",
"Myanmar",
"Montenegro",
"Mongolia",
"Mozambique",
"Mauritania",
"Mauritius",
"Malawi",
"Malaysia",
"Mayotte",
"Namibia",
"Niger",
"Nigeria",
"Nicaragua",
"Nederland",
"Nord-Korea",
"Nord-Marianene",
"Norge",
"Nepal",
"Nauru",
"Ny-Zealand",
"Oman",
"Pakistan",
"Panama",
"Peru",
"Filippinene",
"Palau",
"Palestina",
"Papua Ny-Guinea",
"Polen",
"Portugal",
"Puerto Rico",
"Paraguay",
"Qatar",
"Romania",
"Russland",
"Rwanda",
"Saudi-Arabia",
"Sudan",
"Senegal",
"Singapore",
"Salomonøyene",
"Sierra Leone",
"El Salvador",
"San Marino",
"Somalia",
"Serbia",
"Sør-Sudan",
"São Tomé og Principe",
"Surinam",
"Slovakia",
"Slovenia",
"Sverige",
"Swaziland",
"Seychellene",
"Syria",
"Tsjad",
"Togo",
"Thailand",
"Tadsjikistan",
"Taiwan",
"Turkmenistan",
"Øst-Timor",
"Tonga",
"Trinidad og Tobago",
"Tunisia",
"Tyrkia",
"Tuvalu",
"Tanzania",
"Uganda",
"Ukraina",
"Uruguay",
"USA",
"Usbekistan",
"Vatikanstaten",
"Saint Vincent og Grenadinene",
"Venezuela",
"Vietnam",
"Vanuatu",
"Vest-Sahara",
"Samoa",
"Jemen",
"Sør-Afrika",
"Zambia",
"Zimbabwe"]

console.log(allCountriesEN.length, allCountriesNO.length)
let string="CountryLUT={"
for (let i = 0; i < allCountriesEN.length; i++) {
    string+='"'+allCountriesEN[i]+'":"'+allCountriesNO[i]+'",'
}
console.log(string+'}')



CountryLUT = {
"Angola":"Angola",
"Antigua and Barbuda":"Antigua og Barbuda",
"Afghanistan":"Afghanistan",
"Albania":"Albania",
"United Arab Emirates":"De forente arabiske emirater",
"Argentina":"Argentina",
"Armenia":"Armenia",
"Australia":"Australia",
"Austria":"Østerrike",
"Azerbaijan":"Aserbajdsjan",
"Burundi":"Burundi",
"Belgium":"Belgia",
"Benin":"Benin",
"Burkina Faso":"Burkina Faso",
"Bangladesh":"Bangladesh",
"Bulgaria":"Bulgaria",
"Bahrain":"Bahrain",
"Bahamas":"Bahamas",
"Bosnia and Herzegovina":"Bosnia-Hercegovina",
"Belarus":"Hviterussland",
"Belize":"Belize",
"Bolivia":"Bolivia",
"Brazil":"Brasil",
"Barbados":"Barbados",
"Brunei":"Brunei",
"Bhutan":"Bhutan",
"Botswana":"Botswana",
"Central African Republic":"Den sentralafrikanske republikk",
"Canada":"Canada",
"Switzerland":"Sveits",
"Chile":"Chile",
"China":"Kina",
"Ivory Coast":"Elfenbenskysten",
"Cameroon":"Kamerun",
"Democratic Republic of the Congo":"Den demokratiske republikken Kongo",
"Republic of Congo":"Republikken Kongo",
"Colombia":"Colombia",
"Comoros":"Komorene",
"Cape Verde":"Kapp Verde",
"Costa Rica":"Costa Rica",
"Cuba":"Cuba",
"Cyprus":"Kypros",
"Czech Republic":"Tsjekkia",
"Czechia":"Tsjekkia",
"Germany":"Tyskland",
"Djibouti":"Djibouti",
"Dominica":"Dominica",
"Denmark":"Danmark",
"Greenland":"Grønland",
"Dominican Republic":"Den dominikanske republikken",
"Algeria":"Algerie",
"Ecuador":"Ecuador",
"Egypt":"Egypt",
"Eritrea":"Eritrea",
"Spain":"Spania",
"Canary Islands (Spain)":"Kanariøyene (Spania)",
"Estonia":"Estland",
"Ethiopia":"Etiopia",
"Faeroe Islands":"Færøyene",
"Falkland Islands":"Falklandsøyene",
"Finland":"Finland",
"Fiji":"Fiji",
"France":"Frankrike",
"French Polynesia":"Fransk Polynesia",
"Saint-Barthélemy":"Saint-Barthélemy",
"Saint-Martin":"Saint-Martin",
"French Guiana":"Fransk Guyana",
"Federated States of Micronesia":"Federerte stater i Mikronesia",
"Gabon":"Gabon",
"United Kingdom":"Storbritannia",
"Cayman Islands":"Caymanøyene",
"Turks and Caicos Islands":"Turks- og Caicosøyene",
"Georgia":"Georgia",
"Ghana":"Ghana",
"The Gambia":"Gambia",
"Guinea":"Guinea",
"Guinea-Bissau":"Guinea-Bissau",
"Equatorial Guinea":"Ekvatorial Guinea",
"Greece":"Hellas",
"Grenada":"Grenada",
"Guadeloupe":"Guadeloupe",
"Guatemala":"Guatemala",
"Guam":"Guam",
"Guyana":"Guyana",
"Honduras":"Honduras",
"Croatia":"Kroatia",
"Haiti":"Haiti",
"Hungary":"Ungarn",
"Indonesia":"Indonesia",
"India":"India",
"Ireland":"Irland",
"Iran":"Iran",
"Iraq":"Irak",
"Iceland":"Island",
"Israel":"Israel",
"Italy":"Italia",
"Jamaica":"Jamaica",
"Jordan":"Jordan",
"Japan":"Japan",
"Kazakhstan":"Kasakhstan",
"Kenya":"Kenya",
"Kosovo":"Kosovo",
"Kyrgyzstan":"Kirgisistan",
"Cambodia":"Kambodsja",
"Kiribati":"Kiribati",
"Saint Kitts and Nevis":"Saint Kitts og Nevis",
"South Korea":"Sør-Korea",
"Kuwait":"Kuwait",
"Laos":"Laos",
"Lebanon":"Libanon",
"Liberia":"Liberia",
"Libya":"Libya",
"Saint Lucia":"Saint Lucia",
"Liechtenstein":"Liechtenstein",
"Sri Lanka":"Sri Lanka",
"Lesotho":"Lesotho",
"Lithuania":"Litauen",
"Luxembourg":"Luxembourg",
"Latvia":"Latvia",
"Morocco":"Marokko",
"Monaco":"Monaco",
"Moldova":"Moldova",
"Madagascar":"Madagaskar",
"Maldives":"Maldivene",
"Mexico":"Mexico",
"Marshall Islands":"Marshalløyene",
"Martinique":"Martinique",
"Macedonia":"Nord-Makedonia",
"Mali":"Mali",
"Malta":"Malta",
"Myanmar":"Myanmar",
"Montenegro":"Montenegro",
"Mongolia":"Mongolia",
"Mozambique":"Mozambique",
"Mauritania":"Mauritania",
"Mauritius":"Mauritius",
"Malawi":"Malawi",
"Malaysia":"Malaysia",
"Mayotte":"Mayotte",
"Namibia":"Namibia",
"Niger":"Niger",
"Nigeria":"Nigeria",
"Nicaragua":"Nicaragua",
"Netherlands":"Nederland",
"North Korea":"Nord-Korea",
"Northern Mariana Islands":"Nord-Marianene",
"Norway":"Norge",
"Nepal":"Nepal",
"Nauru":"Nauru",
"New Zealand":"Ny-Zealand",
"Oman":"Oman",
"Pakistan":"Pakistan",
"Panama":"Panama",
"Peru":"Peru",
"Philippines":"Filippinene",
"Palau":"Palau",
"Palestine":"Palestina",
"Papua New Guinea":"Papua Ny-Guinea",
"Poland":"Polen",
"Portugal":"Portugal",
"Puerto Rico":"Puerto Rico",
"Paraguay":"Paraguay",
"Qatar":"Qatar",
"Romania":"Romania",
"Russia":"Russland",
"Rwanda":"Rwanda",
"Saudi Arabia":"Saudi-Arabia",
"Sudan":"Sudan",
"Senegal":"Senegal",
"Singapore":"Singapore",
"Solomon Islands":"Salomonøyene",
"Sierra Leone":"Sierra Leone",
"El Salvador":"El Salvador",
"San Marino":"San Marino",
"Somalia":"Somalia",
"Serbia":"Serbia",
"South Sudan":"Sør-Sudan",
"São Tomé and Principe":"São Tomé og Principe",
"Suriname":"Surinam",
"Slovakia":"Slovakia",
"Slovenia":"Slovenia",
"Sweden":"Sverige",
"Swaziland":"Eswatini",
"Eswatini":"Eswatini",
"Seychelles":"Seychellene",
"Syria":"Syria",
"Chad":"Tsjad",
"Togo":"Togo",
"Thailand":"Thailand",
"Tajikistan":"Tadsjikistan",
"Taiwan":"Taiwan",
"Turkmenistan":"Turkmenistan",
"Timor-Leste":"Øst-Timor",
"Tonga":"Tonga",
"Trinidad and Tobago":"Trinidad og Tobago",
"Tunisia":"Tunisia",
"Turkey":"Tyrkia",
"Tuvalu":"Tuvalu",
"Tanzania":"Tanzania",
"Uganda":"Uganda",
"Ukraine":"Ukraina",
"Uruguay":"Uruguay",
"United States":"De forente stater",
"Uzbekistan":"Usbekistan",
"Vatican City":"Vatikanstaten",
"Saint Vincent and the Grenadines":"Saint Vincent og Grenadinene",
"Venezuela":"Venezuela",
"Vietnam":"Vietnam",
"Vanuatu":"Vanuatu",
"Western Sahara":"Vest-Sahara",
"Samoa":"Samoa",
"Yemen":"Jemen",
"South Africa":"Sør-Afrika",
"Zambia":"Zambia",
"Zimbabwe":"Zimbabwe"}